import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { MetaData, SummaryStats, NavDataPoint, HoldoutData } from "@/types/data";
import { fmtPct, fmtNumber } from "@/lib/formatters";

export const runtime = "nodejs";

const escape = (value: unknown) => String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);

export async function GET(request: Request) {
  const directory = join(process.cwd(), "public", "data");
  const [metaText, summaryText, navText, holdoutText] = await Promise.all([
    readFile(join(directory, "meta.json"), "utf8"), readFile(join(directory, "summary_stats.json"), "utf8"),
    readFile(join(directory, "nav_series.json"), "utf8"), readFile(join(directory, "holdout_analysis.json"), "utf8"),
  ]);
  const meta: MetaData = JSON.parse(metaText);
  const summary: SummaryStats = JSON.parse(summaryText);
  const nav: NavDataPoint[] = JSON.parse(navText);
  const holdout: HoldoutData = JSON.parse(holdoutText);
  const points = nav.filter((_, i) => i % 8 === 0 || i === nav.length - 1);
  const values = points.flatMap(p => [p.strategy_net, p.benchmark]).filter((v): v is number => v != null);
  const low = Math.min(...values);
  const high = Math.max(...values);
  const line = (key: "strategy_net" | "benchmark") => points.filter(p => p[key] != null).map(p => {
    const x = 35 + nav.indexOf(p) / Math.max(1, nav.length - 1) * 620;
    const y = 220 - ((p[key]! - low) / Math.max(.0001, high - low)) * 180;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(" ");
  const rows = [["CAGR", "annualized_return"], ["Annualized volatility", "annualized_volatility"], ["Maximum drawdown", "max_drawdown"]] as const;
  const table = rows.map(([label, key]) => `<tr><th>${label}</th><td>${fmtPct(summary.strategy_net[key])}</td><td>${fmtPct(summary.benchmark[key])}</td></tr>`).join("");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>QFI Research Brief — Sarthak Gupta</title><style>
  *{box-sizing:border-box}body{margin:0;background:#e7e9ec;color:#172134;font:14px/1.65 Arial,sans-serif}a{color:#1768e5}.toolbar{max-width:820px;margin:24px auto;color:#526075}.sheet{width:min(820px,100%);min-height:1020px;margin:24px auto;padding:64px;background:#f7f6f2}.label{font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#1768e5}.folio{display:flex;justify-content:space-between;border-top:1px solid #cdd2d9;padding-top:15px;margin-top:38px;color:#617085;font-size:11px}h1{font-size:56px;line-height:1.04;letter-spacing:-3px;font-weight:500;margin:48px 0 25px}h2{font-size:34px;line-height:1.1;letter-spacing:-1px;font-weight:500}h3{font-size:19px;line-height:1.3}p{color:#526075}table{width:100%;border-collapse:collapse;margin:22px 0}td,th{border-bottom:1px solid #d9dce0;padding:12px 5px;text-align:right}th:first-child{text-align:left}small{color:#617085}.callout{background:#e9eff7;padding:22px;border-left:3px solid #1768e5;margin:25px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:30px}svg{width:100%;height:auto}li{margin-bottom:10px}code{overflow-wrap:anywhere}.print-note{font-size:12px}@media(max-width:600px){.sheet{padding:28px;min-height:0}.grid{grid-template-columns:1fr}h1{font-size:42px}}@page{size:A4;margin:14mm}@media print{body{background:white;font-size:10pt;line-height:1.5}.toolbar{display:none}.sheet{width:100%;min-height:0;margin:0;padding:0;break-after:page;background:white}.sheet:last-child{break-after:auto}h1{font-size:36pt;margin-top:30px}h2{font-size:25pt}table,.callout,svg{break-inside:avoid}a{color:inherit;text-decoration:none}.folio{margin-top:25px}p{color:#394454}}
  </style></head><body><div class="toolbar"><a href="/">← Research website</a><p class="print-note">Three-page research brief. Use your browser’s Print → Save as PDF. All figures are read from the saved project outputs.</p></div>
  <section class="sheet"><div class="label">QFI / Independent quantitative research</div><h1>Fixed-Income<br>Strategy &amp;<br>Risk Research.</h1><p>Sarthak Gupta · BBA — Decision Science</p><div class="callout"><strong>The question</strong><p>Can a transparent rules-based framework adapt Treasury exposure using momentum and realized volatility?</p></div><h3>The framework</h3><p>${meta.momentum_window_days}-day momentum controls eligibility for IEF and TLT. SHY remains the defensive asset. Eligible assets are sized using inverse ${meta.volatility_window_days}-day realized volatility, with monthly rebalancing and next-available-trading-day implementation.</p><h3>The findings—and the trade-off</h3><table><thead><tr><th>Full-history measure</th><th>Net strategy</th><th>AGG</th></tr></thead><tbody>${table}<tr><th>Sharpe · Rf ${meta.risk_free_rate_annual * 100}%</th><td>${fmtNumber(summary.strategy_net.sharpe_ratio, 2)}</td><td>${fmtNumber(summary.benchmark.sharpe_ratio, 2)}</td></tr></tbody></table><p>Lower historical volatility and drawdown accompanied a lower CAGR than AGG. This is a historical trade-off, not evidence of future superiority.</p><small>Evaluation: ${escape(meta.start_date)} – ${escape(meta.end_date)}. Net strategy includes ${meta.transaction_cost_bps} bps × gross traded notional.</small><div class="folio"><span>Historical snapshot · not live investment data</span><span>01 / 03</span></div></section>
  <section class="sheet"><div class="label">Evidence / the historical path</div><h2>Results are a path,<br>not just a headline.</h2><h3>Growth of one unit</h3><svg viewBox="0 0 690 275" role="img" aria-label="Saved historical strategy and AGG NAV"><path d="M35 220H655 M35 160H655 M35 100H655 M35 40H655" stroke="#d9dce0" fill="none"/><polyline points="${line("benchmark")}" stroke="#8c99a9" stroke-width="2" fill="none"/><polyline points="${line("strategy_net")}" stroke="#1768e5" stroke-width="3" fill="none"/><text x="35" y="252" fill="#617085">${escape(meta.start_date.slice(0, 4))}</text><text x="620" y="252" fill="#617085">${escape(meta.end_date.slice(0, 4))}</text><text x="6" y="225" fill="#617085">${low.toFixed(1)}</text><text x="6" y="45" fill="#617085">${high.toFixed(1)}</text></svg><small>Blue: net strategy · grey: AGG. Original NAV base retained. Display sampled from saved observations.</small><h3>A later holdout, with fixed rules</h3><p>${escape(holdout.periods.holdout.start_date)} – ${escape(holdout.periods.holdout.end_date)}. No parameter was selected using holdout results.</p><table><thead><tr><th>Holdout measure</th><th>Net strategy</th><th>AGG</th></tr></thead><tbody><tr><th>CAGR</th><td>${fmtPct(holdout.periods.holdout.strategy.cagr)}</td><td>${fmtPct(holdout.periods.holdout.benchmark.cagr)}</td></tr><tr><th>Volatility</th><td>${fmtPct(holdout.periods.holdout.strategy.annualized_volatility)}</td><td>${fmtPct(holdout.periods.holdout.benchmark.annualized_volatility)}</td></tr><tr><th>Maximum drawdown</th><td>${fmtPct(holdout.periods.holdout.strategy.maximum_drawdown)}</td><td>${fmtPct(holdout.periods.holdout.benchmark.maximum_drawdown)}</td></tr></tbody></table><div class="callout"><strong>Inspect the adverse evidence</strong><p>The website includes ranked drawdowns, worst calendar periods, fixed-parameter sensitivity and observed allocations. Whole-period metrics have explicit evaluation dates; sensitivity uses its own common window.</p></div><div class="folio"><span>Fixed parameters · saved evidence · no new calculations</span><span>02 / 03</span></div></section>
  <section class="sheet"><div class="label">Method / provenance / limits</div><h2>Transparent assumptions.<br>Explicit boundaries.</h2><div class="grid"><div><h3>Data and implementation</h3><ul><li>Yahoo Finance adjusted close via yfinance, used as a total-return proxy.</li><li>Universe: ${escape(meta.tickers.join(", "))}; passive reference: ${escape(meta.benchmark)}.</li><li>Monthly signals at the close; target weights active on the next available trading day.</li><li>No leverage; fractional positions allowed.</li><li>${meta.transaction_cost_bps} bps cost on gross traded notional; ${meta.risk_free_rate_annual * 100}% annual risk-free-rate assumption.</li></ul></div><div><h3>Limits of the evidence</h3><ul><li>Historical simulation, not a live execution record.</li><li>Vendor data may be revised; ETF proxies do not reproduce every fixed-income market segment.</li><li>Taxes, market impact and additional frictions are excluded.</li><li>Rate shocks are duration-only approximations using fixed issuer snapshots.</li><li>Historical co-occurrence does not establish causality.</li></ul></div></div><h3>Reproduce and inspect</h3><p><a href="https://github.com/Sarthak-gupta04/quantitative-fixed-income-research">github.com/Sarthak-gupta04/quantitative-fixed-income-research</a></p><p>The repository records parameters, saved raw-data hashes, tests and reproduction instructions. A new vendor download is not guaranteed to reproduce this snapshot byte-for-byte.</p><h3>Sources</h3><p>Yahoo Finance / yfinance (ETF adjusted prices); U.S. Department of the Treasury (par yields); iShares (ETF documentation and effective durations). Detailed source links and saved provenance are available on the website and in the repository.</p><div class="callout"><strong>Important disclosure</strong><p>${escape(meta.disclaimer)}</p></div><small>Market data through ${escape(meta.end_date)}. Outputs generated ${escape(meta.generated_at_utc)}. This document does not refresh market data or rerun the research engine.</small><div class="folio"><span>Sarthak Gupta / Independent research</span><span>03 / 03</span></div></section></body></html>`;
  return new Response(html, { headers: {
    "Content-Type": "text/html; charset=utf-8",
    "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'",
    "X-Content-Type-Options": "nosniff",
    ...(new URL(request.url).searchParams.get("download") === "1" ? { "Content-Disposition": 'attachment; filename="qfi-research-brief.html"' } : {}),
  } });
}
